import type { Metadata } from "next";
import { Poppins  } from "next/font/google";
import "./globals.css";
import Navbar from './Navbar'
import Connect from './Connect'
import Add from './Add'
import Testimonial from './Testimonial'
import Footer from './Footer'

const poppins = Poppins({
  subsets: ['latin'], 
  display: 'swap', 
  variable: '--font-poppins', 
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar/>
        {children} 
        <Connect/> 
        <Add/>
        <Testimonial/>
        <Footer/>
        </body>
    </html>
  );
}
